FROM node:24-alpine AS base
RUN corepack enable && corepack prepare pnpm@11 --activate

FROM base AS deps

WORKDIR /app
COPY ./client_app/package.json ./client_app/pnpm-lock.yaml ./client_app/pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

FROM deps AS builder

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY ./client_app/ .
COPY ./generated_configs/client_config.toml ./client_config.toml

ENV NODE_ENV=production
ENV DOCKER_BUILD=true
ENV CI=true

RUN pnpm run build

FROM gcr.io/distroless/nodejs24-debian13 AS distroless

WORKDIR /app

COPY --from=builder --chown=nextjs:nextjs /app/client_config.toml ./client_config.toml
COPY --from=builder --chown=nextjs:nextjs /app/.next/standalone/ ./
COPY --from=builder --chown=nextjs:nextjs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nextjs /app/public ./public

EXPOSE 3000

USER nonroot

CMD ["server.js"]
