// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: solve_route.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Cogwheel-Validator/spectra-ibc-hub/solver/rpc/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SolverServiceName is the fully-qualified name of the SolverService service.
	SolverServiceName = "rpc.v1.SolverService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SolverServiceSolveRouteProcedure is the fully-qualified name of the SolverService's SolveRoute
	// RPC.
	SolverServiceSolveRouteProcedure = "/rpc.v1.SolverService/SolveRoute"
	// SolverServiceLookupDenomProcedure is the fully-qualified name of the SolverService's LookupDenom
	// RPC.
	SolverServiceLookupDenomProcedure = "/rpc.v1.SolverService/LookupDenom"
	// SolverServiceGetTokenDenomsProcedure is the fully-qualified name of the SolverService's
	// GetTokenDenoms RPC.
	SolverServiceGetTokenDenomsProcedure = "/rpc.v1.SolverService/GetTokenDenoms"
	// SolverServiceGetChainInfoProcedure is the fully-qualified name of the SolverService's
	// GetChainInfo RPC.
	SolverServiceGetChainInfoProcedure = "/rpc.v1.SolverService/GetChainInfo"
	// SolverServiceGetSolverSupportedChainsProcedure is the fully-qualified name of the SolverService's
	// GetSolverSupportedChains RPC.
	SolverServiceGetSolverSupportedChainsProcedure = "/rpc.v1.SolverService/GetSolverSupportedChains"
	// SolverServiceGetChainTokensProcedure is the fully-qualified name of the SolverService's
	// GetChainTokens RPC.
	SolverServiceGetChainTokensProcedure = "/rpc.v1.SolverService/GetChainTokens"
)

// SolverServiceClient is a client for the rpc.v1.SolverService service.
type SolverServiceClient interface {
	// SolveRoute finds and validates a route between two chains
	// Supports human-readable denoms (e.g., "uatone") or IBC denoms
	SolveRoute(context.Context, *connect.Request[v1.SolveRouteRequest]) (*connect.Response[v1.SolveRouteResponse], error)
	// LookupDenom resolves denom information on a specific chain
	// Accepts human-readable base denoms or IBC denom hashes
	LookupDenom(context.Context, *connect.Request[v1.LookupDenomRequest]) (*connect.Response[v1.LookupDenomResponse], error)
	// GetTokenDenoms returns all IBC denoms for a token across supported chains
	// Use this to discover what denom a token has on different chains
	GetTokenDenoms(context.Context, *connect.Request[v1.GetTokenDenomsRequest]) (*connect.Response[v1.GetTokenDenomsResponse], error)
	// GetChainInfo returns information about a specific chain
	GetChainInfo(context.Context, *connect.Request[v1.ChainInfoRequest]) (*connect.Response[v1.ChainInfoResponse], error)
	// GetSolverSupportedChains returns a list of supported chains
	GetSolverSupportedChains(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.SolverSupportedChainsResponse], error)
	// GetChainTokens returns all tokens available on a specific chain
	// Includes both native tokens and IBC tokens with their denoms
	GetChainTokens(context.Context, *connect.Request[v1.GetChainTokensRequest]) (*connect.Response[v1.GetChainTokensResponse], error)
}

// NewSolverServiceClient constructs a client for the rpc.v1.SolverService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSolverServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SolverServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	solverServiceMethods := v1.File_solve_route_proto.Services().ByName("SolverService").Methods()
	return &solverServiceClient{
		solveRoute: connect.NewClient[v1.SolveRouteRequest, v1.SolveRouteResponse](
			httpClient,
			baseURL+SolverServiceSolveRouteProcedure,
			connect.WithSchema(solverServiceMethods.ByName("SolveRoute")),
			connect.WithClientOptions(opts...),
		),
		lookupDenom: connect.NewClient[v1.LookupDenomRequest, v1.LookupDenomResponse](
			httpClient,
			baseURL+SolverServiceLookupDenomProcedure,
			connect.WithSchema(solverServiceMethods.ByName("LookupDenom")),
			connect.WithClientOptions(opts...),
		),
		getTokenDenoms: connect.NewClient[v1.GetTokenDenomsRequest, v1.GetTokenDenomsResponse](
			httpClient,
			baseURL+SolverServiceGetTokenDenomsProcedure,
			connect.WithSchema(solverServiceMethods.ByName("GetTokenDenoms")),
			connect.WithClientOptions(opts...),
		),
		getChainInfo: connect.NewClient[v1.ChainInfoRequest, v1.ChainInfoResponse](
			httpClient,
			baseURL+SolverServiceGetChainInfoProcedure,
			connect.WithSchema(solverServiceMethods.ByName("GetChainInfo")),
			connect.WithClientOptions(opts...),
		),
		getSolverSupportedChains: connect.NewClient[emptypb.Empty, v1.SolverSupportedChainsResponse](
			httpClient,
			baseURL+SolverServiceGetSolverSupportedChainsProcedure,
			connect.WithSchema(solverServiceMethods.ByName("GetSolverSupportedChains")),
			connect.WithClientOptions(opts...),
		),
		getChainTokens: connect.NewClient[v1.GetChainTokensRequest, v1.GetChainTokensResponse](
			httpClient,
			baseURL+SolverServiceGetChainTokensProcedure,
			connect.WithSchema(solverServiceMethods.ByName("GetChainTokens")),
			connect.WithClientOptions(opts...),
		),
	}
}

// solverServiceClient implements SolverServiceClient.
type solverServiceClient struct {
	solveRoute               *connect.Client[v1.SolveRouteRequest, v1.SolveRouteResponse]
	lookupDenom              *connect.Client[v1.LookupDenomRequest, v1.LookupDenomResponse]
	getTokenDenoms           *connect.Client[v1.GetTokenDenomsRequest, v1.GetTokenDenomsResponse]
	getChainInfo             *connect.Client[v1.ChainInfoRequest, v1.ChainInfoResponse]
	getSolverSupportedChains *connect.Client[emptypb.Empty, v1.SolverSupportedChainsResponse]
	getChainTokens           *connect.Client[v1.GetChainTokensRequest, v1.GetChainTokensResponse]
}

// SolveRoute calls rpc.v1.SolverService.SolveRoute.
func (c *solverServiceClient) SolveRoute(ctx context.Context, req *connect.Request[v1.SolveRouteRequest]) (*connect.Response[v1.SolveRouteResponse], error) {
	return c.solveRoute.CallUnary(ctx, req)
}

// LookupDenom calls rpc.v1.SolverService.LookupDenom.
func (c *solverServiceClient) LookupDenom(ctx context.Context, req *connect.Request[v1.LookupDenomRequest]) (*connect.Response[v1.LookupDenomResponse], error) {
	return c.lookupDenom.CallUnary(ctx, req)
}

// GetTokenDenoms calls rpc.v1.SolverService.GetTokenDenoms.
func (c *solverServiceClient) GetTokenDenoms(ctx context.Context, req *connect.Request[v1.GetTokenDenomsRequest]) (*connect.Response[v1.GetTokenDenomsResponse], error) {
	return c.getTokenDenoms.CallUnary(ctx, req)
}

// GetChainInfo calls rpc.v1.SolverService.GetChainInfo.
func (c *solverServiceClient) GetChainInfo(ctx context.Context, req *connect.Request[v1.ChainInfoRequest]) (*connect.Response[v1.ChainInfoResponse], error) {
	return c.getChainInfo.CallUnary(ctx, req)
}

// GetSolverSupportedChains calls rpc.v1.SolverService.GetSolverSupportedChains.
func (c *solverServiceClient) GetSolverSupportedChains(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1.SolverSupportedChainsResponse], error) {
	return c.getSolverSupportedChains.CallUnary(ctx, req)
}

// GetChainTokens calls rpc.v1.SolverService.GetChainTokens.
func (c *solverServiceClient) GetChainTokens(ctx context.Context, req *connect.Request[v1.GetChainTokensRequest]) (*connect.Response[v1.GetChainTokensResponse], error) {
	return c.getChainTokens.CallUnary(ctx, req)
}

// SolverServiceHandler is an implementation of the rpc.v1.SolverService service.
type SolverServiceHandler interface {
	// SolveRoute finds and validates a route between two chains
	// Supports human-readable denoms (e.g., "uatone") or IBC denoms
	SolveRoute(context.Context, *connect.Request[v1.SolveRouteRequest]) (*connect.Response[v1.SolveRouteResponse], error)
	// LookupDenom resolves denom information on a specific chain
	// Accepts human-readable base denoms or IBC denom hashes
	LookupDenom(context.Context, *connect.Request[v1.LookupDenomRequest]) (*connect.Response[v1.LookupDenomResponse], error)
	// GetTokenDenoms returns all IBC denoms for a token across supported chains
	// Use this to discover what denom a token has on different chains
	GetTokenDenoms(context.Context, *connect.Request[v1.GetTokenDenomsRequest]) (*connect.Response[v1.GetTokenDenomsResponse], error)
	// GetChainInfo returns information about a specific chain
	GetChainInfo(context.Context, *connect.Request[v1.ChainInfoRequest]) (*connect.Response[v1.ChainInfoResponse], error)
	// GetSolverSupportedChains returns a list of supported chains
	GetSolverSupportedChains(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.SolverSupportedChainsResponse], error)
	// GetChainTokens returns all tokens available on a specific chain
	// Includes both native tokens and IBC tokens with their denoms
	GetChainTokens(context.Context, *connect.Request[v1.GetChainTokensRequest]) (*connect.Response[v1.GetChainTokensResponse], error)
}

// NewSolverServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSolverServiceHandler(svc SolverServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	solverServiceMethods := v1.File_solve_route_proto.Services().ByName("SolverService").Methods()
	solverServiceSolveRouteHandler := connect.NewUnaryHandler(
		SolverServiceSolveRouteProcedure,
		svc.SolveRoute,
		connect.WithSchema(solverServiceMethods.ByName("SolveRoute")),
		connect.WithHandlerOptions(opts...),
	)
	solverServiceLookupDenomHandler := connect.NewUnaryHandler(
		SolverServiceLookupDenomProcedure,
		svc.LookupDenom,
		connect.WithSchema(solverServiceMethods.ByName("LookupDenom")),
		connect.WithHandlerOptions(opts...),
	)
	solverServiceGetTokenDenomsHandler := connect.NewUnaryHandler(
		SolverServiceGetTokenDenomsProcedure,
		svc.GetTokenDenoms,
		connect.WithSchema(solverServiceMethods.ByName("GetTokenDenoms")),
		connect.WithHandlerOptions(opts...),
	)
	solverServiceGetChainInfoHandler := connect.NewUnaryHandler(
		SolverServiceGetChainInfoProcedure,
		svc.GetChainInfo,
		connect.WithSchema(solverServiceMethods.ByName("GetChainInfo")),
		connect.WithHandlerOptions(opts...),
	)
	solverServiceGetSolverSupportedChainsHandler := connect.NewUnaryHandler(
		SolverServiceGetSolverSupportedChainsProcedure,
		svc.GetSolverSupportedChains,
		connect.WithSchema(solverServiceMethods.ByName("GetSolverSupportedChains")),
		connect.WithHandlerOptions(opts...),
	)
	solverServiceGetChainTokensHandler := connect.NewUnaryHandler(
		SolverServiceGetChainTokensProcedure,
		svc.GetChainTokens,
		connect.WithSchema(solverServiceMethods.ByName("GetChainTokens")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpc.v1.SolverService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SolverServiceSolveRouteProcedure:
			solverServiceSolveRouteHandler.ServeHTTP(w, r)
		case SolverServiceLookupDenomProcedure:
			solverServiceLookupDenomHandler.ServeHTTP(w, r)
		case SolverServiceGetTokenDenomsProcedure:
			solverServiceGetTokenDenomsHandler.ServeHTTP(w, r)
		case SolverServiceGetChainInfoProcedure:
			solverServiceGetChainInfoHandler.ServeHTTP(w, r)
		case SolverServiceGetSolverSupportedChainsProcedure:
			solverServiceGetSolverSupportedChainsHandler.ServeHTTP(w, r)
		case SolverServiceGetChainTokensProcedure:
			solverServiceGetChainTokensHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSolverServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSolverServiceHandler struct{}

func (UnimplementedSolverServiceHandler) SolveRoute(context.Context, *connect.Request[v1.SolveRouteRequest]) (*connect.Response[v1.SolveRouteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.v1.SolverService.SolveRoute is not implemented"))
}

func (UnimplementedSolverServiceHandler) LookupDenom(context.Context, *connect.Request[v1.LookupDenomRequest]) (*connect.Response[v1.LookupDenomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.v1.SolverService.LookupDenom is not implemented"))
}

func (UnimplementedSolverServiceHandler) GetTokenDenoms(context.Context, *connect.Request[v1.GetTokenDenomsRequest]) (*connect.Response[v1.GetTokenDenomsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.v1.SolverService.GetTokenDenoms is not implemented"))
}

func (UnimplementedSolverServiceHandler) GetChainInfo(context.Context, *connect.Request[v1.ChainInfoRequest]) (*connect.Response[v1.ChainInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.v1.SolverService.GetChainInfo is not implemented"))
}

func (UnimplementedSolverServiceHandler) GetSolverSupportedChains(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.SolverSupportedChainsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.v1.SolverService.GetSolverSupportedChains is not implemented"))
}

func (UnimplementedSolverServiceHandler) GetChainTokens(context.Context, *connect.Request[v1.GetChainTokensRequest]) (*connect.Response[v1.GetChainTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.v1.SolverService.GetChainTokens is not implemented"))
}
