version: v2
inputs:
  - directory: .
    paths:
      - pathfinder/v2beta
plugins:
  - local: protoc-gen-connect-openapi
    out: ../docs/openapi
    opt:
      - format=yaml
      - path=v2beta.openapi.yaml
      - with-streaming
      - content-types=json;proto
