allowBuilds:
  "@bufbuild/buf": true
  "esbuild": true
  "sharp": true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - next
  - "@next/swc-*"
  - "@next/env"
  - react
  - react-dom
  - "@types/node"
  - "@types/react"
  - "@types/react-dom"
  - "@next/env"
  - "@next/swc-darwin-arm64"
  - "@next/swc-darwin-x64"
  - "@next/swc-linux-arm64-gnu"
  - "@next/swc-linux-arm64-musl"
  - "@next/swc-linux-x64-gnu"
  - "@next/swc-linux-x64-musl"
  - "@next/swc-win32-arm64-msvc"
  - "@next/swc-win32-x64-msvc"
overrides:
  "ws": "7.5.11"
