// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pathfinder_route.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Cogwheel-Validator/spectra-portal/pathfinder/rpc/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PathfinderServiceName is the fully-qualified name of the PathfinderService service.
	PathfinderServiceName = "pathfinder.v1.PathfinderService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PathfinderServiceFindPathProcedure is the fully-qualified name of the PathfinderService's
	// FindPath RPC.
	PathfinderServiceFindPathProcedure = "/pathfinder.v1.PathfinderService/FindPath"
	// PathfinderServiceLookupDenomProcedure is the fully-qualified name of the PathfinderService's
	// LookupDenom RPC.
	PathfinderServiceLookupDenomProcedure = "/pathfinder.v1.PathfinderService/LookupDenom"
	// PathfinderServiceGetTokenDenomsProcedure is the fully-qualified name of the PathfinderService's
	// GetTokenDenoms RPC.
	PathfinderServiceGetTokenDenomsProcedure = "/pathfinder.v1.PathfinderService/GetTokenDenoms"
	// PathfinderServiceGetChainInfoProcedure is the fully-qualified name of the PathfinderService's
	// GetChainInfo RPC.
	PathfinderServiceGetChainInfoProcedure = "/pathfinder.v1.PathfinderService/GetChainInfo"
	// PathfinderServiceListSupportedChainsProcedure is the fully-qualified name of the
	// PathfinderService's ListSupportedChains RPC.
	PathfinderServiceListSupportedChainsProcedure = "/pathfinder.v1.PathfinderService/ListSupportedChains"
	// PathfinderServiceGetChainTokensProcedure is the fully-qualified name of the PathfinderService's
	// GetChainTokens RPC.
	PathfinderServiceGetChainTokensProcedure = "/pathfinder.v1.PathfinderService/GetChainTokens"
)

// PathfinderServiceClient is a client for the pathfinder.v1.PathfinderService service.
type PathfinderServiceClient interface {
	// FindPath finds and validates a route between two chains
	// Supports human-readable denoms (e.g., "uatone") or IBC denoms
	FindPath(context.Context, *connect.Request[v1.FindPathRequest]) (*connect.Response[v1.FindPathResponse], error)
	// LookupDenom resolves denom information on a specific chain
	// Accepts human-readable base denoms or IBC denom hashes
	LookupDenom(context.Context, *connect.Request[v1.LookupDenomRequest]) (*connect.Response[v1.LookupDenomResponse], error)
	// GetTokenDenoms returns all IBC denoms for a token across supported chains
	// Use this to discover what denom a token has on different chains
	GetTokenDenoms(context.Context, *connect.Request[v1.GetTokenDenomsRequest]) (*connect.Response[v1.GetTokenDenomsResponse], error)
	// GetChainInfo returns information about a specific chain
	GetChainInfo(context.Context, *connect.Request[v1.ChainInfoRequest]) (*connect.Response[v1.ChainInfoResponse], error)
	// ListSupportedChains returns a list of supported chains
	ListSupportedChains(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.PathfinderSupportedChainsResponse], error)
	// GetChainTokens returns all tokens available on a specific chain
	// Includes both native tokens and IBC tokens with their denoms
	GetChainTokens(context.Context, *connect.Request[v1.GetChainTokensRequest]) (*connect.Response[v1.GetChainTokensResponse], error)
}

// NewPathfinderServiceClient constructs a client for the pathfinder.v1.PathfinderService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPathfinderServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PathfinderServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pathfinderServiceMethods := v1.File_pathfinder_route_proto.Services().ByName("PathfinderService").Methods()
	return &pathfinderServiceClient{
		findPath: connect.NewClient[v1.FindPathRequest, v1.FindPathResponse](
			httpClient,
			baseURL+PathfinderServiceFindPathProcedure,
			connect.WithSchema(pathfinderServiceMethods.ByName("FindPath")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		lookupDenom: connect.NewClient[v1.LookupDenomRequest, v1.LookupDenomResponse](
			httpClient,
			baseURL+PathfinderServiceLookupDenomProcedure,
			connect.WithSchema(pathfinderServiceMethods.ByName("LookupDenom")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getTokenDenoms: connect.NewClient[v1.GetTokenDenomsRequest, v1.GetTokenDenomsResponse](
			httpClient,
			baseURL+PathfinderServiceGetTokenDenomsProcedure,
			connect.WithSchema(pathfinderServiceMethods.ByName("GetTokenDenoms")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getChainInfo: connect.NewClient[v1.ChainInfoRequest, v1.ChainInfoResponse](
			httpClient,
			baseURL+PathfinderServiceGetChainInfoProcedure,
			connect.WithSchema(pathfinderServiceMethods.ByName("GetChainInfo")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listSupportedChains: connect.NewClient[emptypb.Empty, v1.PathfinderSupportedChainsResponse](
			httpClient,
			baseURL+PathfinderServiceListSupportedChainsProcedure,
			connect.WithSchema(pathfinderServiceMethods.ByName("ListSupportedChains")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getChainTokens: connect.NewClient[v1.GetChainTokensRequest, v1.GetChainTokensResponse](
			httpClient,
			baseURL+PathfinderServiceGetChainTokensProcedure,
			connect.WithSchema(pathfinderServiceMethods.ByName("GetChainTokens")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// pathfinderServiceClient implements PathfinderServiceClient.
type pathfinderServiceClient struct {
	findPath            *connect.Client[v1.FindPathRequest, v1.FindPathResponse]
	lookupDenom         *connect.Client[v1.LookupDenomRequest, v1.LookupDenomResponse]
	getTokenDenoms      *connect.Client[v1.GetTokenDenomsRequest, v1.GetTokenDenomsResponse]
	getChainInfo        *connect.Client[v1.ChainInfoRequest, v1.ChainInfoResponse]
	listSupportedChains *connect.Client[emptypb.Empty, v1.PathfinderSupportedChainsResponse]
	getChainTokens      *connect.Client[v1.GetChainTokensRequest, v1.GetChainTokensResponse]
}

// FindPath calls pathfinder.v1.PathfinderService.FindPath.
func (c *pathfinderServiceClient) FindPath(ctx context.Context, req *connect.Request[v1.FindPathRequest]) (*connect.Response[v1.FindPathResponse], error) {
	return c.findPath.CallUnary(ctx, req)
}

// LookupDenom calls pathfinder.v1.PathfinderService.LookupDenom.
func (c *pathfinderServiceClient) LookupDenom(ctx context.Context, req *connect.Request[v1.LookupDenomRequest]) (*connect.Response[v1.LookupDenomResponse], error) {
	return c.lookupDenom.CallUnary(ctx, req)
}

// GetTokenDenoms calls pathfinder.v1.PathfinderService.GetTokenDenoms.
func (c *pathfinderServiceClient) GetTokenDenoms(ctx context.Context, req *connect.Request[v1.GetTokenDenomsRequest]) (*connect.Response[v1.GetTokenDenomsResponse], error) {
	return c.getTokenDenoms.CallUnary(ctx, req)
}

// GetChainInfo calls pathfinder.v1.PathfinderService.GetChainInfo.
func (c *pathfinderServiceClient) GetChainInfo(ctx context.Context, req *connect.Request[v1.ChainInfoRequest]) (*connect.Response[v1.ChainInfoResponse], error) {
	return c.getChainInfo.CallUnary(ctx, req)
}

// ListSupportedChains calls pathfinder.v1.PathfinderService.ListSupportedChains.
func (c *pathfinderServiceClient) ListSupportedChains(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1.PathfinderSupportedChainsResponse], error) {
	return c.listSupportedChains.CallUnary(ctx, req)
}

// GetChainTokens calls pathfinder.v1.PathfinderService.GetChainTokens.
func (c *pathfinderServiceClient) GetChainTokens(ctx context.Context, req *connect.Request[v1.GetChainTokensRequest]) (*connect.Response[v1.GetChainTokensResponse], error) {
	return c.getChainTokens.CallUnary(ctx, req)
}

// PathfinderServiceHandler is an implementation of the pathfinder.v1.PathfinderService service.
type PathfinderServiceHandler interface {
	// FindPath finds and validates a route between two chains
	// Supports human-readable denoms (e.g., "uatone") or IBC denoms
	FindPath(context.Context, *connect.Request[v1.FindPathRequest]) (*connect.Response[v1.FindPathResponse], error)
	// LookupDenom resolves denom information on a specific chain
	// Accepts human-readable base denoms or IBC denom hashes
	LookupDenom(context.Context, *connect.Request[v1.LookupDenomRequest]) (*connect.Response[v1.LookupDenomResponse], error)
	// GetTokenDenoms returns all IBC denoms for a token across supported chains
	// Use this to discover what denom a token has on different chains
	GetTokenDenoms(context.Context, *connect.Request[v1.GetTokenDenomsRequest]) (*connect.Response[v1.GetTokenDenomsResponse], error)
	// GetChainInfo returns information about a specific chain
	GetChainInfo(context.Context, *connect.Request[v1.ChainInfoRequest]) (*connect.Response[v1.ChainInfoResponse], error)
	// ListSupportedChains returns a list of supported chains
	ListSupportedChains(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.PathfinderSupportedChainsResponse], error)
	// GetChainTokens returns all tokens available on a specific chain
	// Includes both native tokens and IBC tokens with their denoms
	GetChainTokens(context.Context, *connect.Request[v1.GetChainTokensRequest]) (*connect.Response[v1.GetChainTokensResponse], error)
}

// NewPathfinderServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPathfinderServiceHandler(svc PathfinderServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pathfinderServiceMethods := v1.File_pathfinder_route_proto.Services().ByName("PathfinderService").Methods()
	pathfinderServiceFindPathHandler := connect.NewUnaryHandler(
		PathfinderServiceFindPathProcedure,
		svc.FindPath,
		connect.WithSchema(pathfinderServiceMethods.ByName("FindPath")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	pathfinderServiceLookupDenomHandler := connect.NewUnaryHandler(
		PathfinderServiceLookupDenomProcedure,
		svc.LookupDenom,
		connect.WithSchema(pathfinderServiceMethods.ByName("LookupDenom")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	pathfinderServiceGetTokenDenomsHandler := connect.NewUnaryHandler(
		PathfinderServiceGetTokenDenomsProcedure,
		svc.GetTokenDenoms,
		connect.WithSchema(pathfinderServiceMethods.ByName("GetTokenDenoms")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	pathfinderServiceGetChainInfoHandler := connect.NewUnaryHandler(
		PathfinderServiceGetChainInfoProcedure,
		svc.GetChainInfo,
		connect.WithSchema(pathfinderServiceMethods.ByName("GetChainInfo")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	pathfinderServiceListSupportedChainsHandler := connect.NewUnaryHandler(
		PathfinderServiceListSupportedChainsProcedure,
		svc.ListSupportedChains,
		connect.WithSchema(pathfinderServiceMethods.ByName("ListSupportedChains")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	pathfinderServiceGetChainTokensHandler := connect.NewUnaryHandler(
		PathfinderServiceGetChainTokensProcedure,
		svc.GetChainTokens,
		connect.WithSchema(pathfinderServiceMethods.ByName("GetChainTokens")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/pathfinder.v1.PathfinderService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PathfinderServiceFindPathProcedure:
			pathfinderServiceFindPathHandler.ServeHTTP(w, r)
		case PathfinderServiceLookupDenomProcedure:
			pathfinderServiceLookupDenomHandler.ServeHTTP(w, r)
		case PathfinderServiceGetTokenDenomsProcedure:
			pathfinderServiceGetTokenDenomsHandler.ServeHTTP(w, r)
		case PathfinderServiceGetChainInfoProcedure:
			pathfinderServiceGetChainInfoHandler.ServeHTTP(w, r)
		case PathfinderServiceListSupportedChainsProcedure:
			pathfinderServiceListSupportedChainsHandler.ServeHTTP(w, r)
		case PathfinderServiceGetChainTokensProcedure:
			pathfinderServiceGetChainTokensHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPathfinderServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPathfinderServiceHandler struct{}

func (UnimplementedPathfinderServiceHandler) FindPath(context.Context, *connect.Request[v1.FindPathRequest]) (*connect.Response[v1.FindPathResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pathfinder.v1.PathfinderService.FindPath is not implemented"))
}

func (UnimplementedPathfinderServiceHandler) LookupDenom(context.Context, *connect.Request[v1.LookupDenomRequest]) (*connect.Response[v1.LookupDenomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pathfinder.v1.PathfinderService.LookupDenom is not implemented"))
}

func (UnimplementedPathfinderServiceHandler) GetTokenDenoms(context.Context, *connect.Request[v1.GetTokenDenomsRequest]) (*connect.Response[v1.GetTokenDenomsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pathfinder.v1.PathfinderService.GetTokenDenoms is not implemented"))
}

func (UnimplementedPathfinderServiceHandler) GetChainInfo(context.Context, *connect.Request[v1.ChainInfoRequest]) (*connect.Response[v1.ChainInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pathfinder.v1.PathfinderService.GetChainInfo is not implemented"))
}

func (UnimplementedPathfinderServiceHandler) ListSupportedChains(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1.PathfinderSupportedChainsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pathfinder.v1.PathfinderService.ListSupportedChains is not implemented"))
}

func (UnimplementedPathfinderServiceHandler) GetChainTokens(context.Context, *connect.Request[v1.GetChainTokensRequest]) (*connect.Response[v1.GetChainTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pathfinder.v1.PathfinderService.GetChainTokens is not implemented"))
}
