// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: pathfinder/v2beta/pathfinder_v2beta_common.proto

package v2beta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenMapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The denom as it appears on the current chain (native or IBC)
	ChainDenom string `protobuf:"bytes,1,opt,name=chain_denom,proto3" json:"chain_denom,omitempty"`
	// The base/native denom on the token's origin chain
	BaseDenom string `protobuf:"bytes,2,opt,name=base_denom,proto3" json:"base_denom,omitempty"`
	// The chain ID where this token is native
	OriginChain string `protobuf:"bytes,3,opt,name=origin_chain,proto3" json:"origin_chain,omitempty"`
	// True if this is the token's native chain
	IsNative bool `protobuf:"varint,4,opt,name=is_native,proto3" json:"is_native,omitempty"`
}

func (x *TokenMapping) Reset() {
	*x = TokenMapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenMapping) ProtoMessage() {}

func (x *TokenMapping) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenMapping.ProtoReflect.Descriptor instead.
func (*TokenMapping) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{0}
}

func (x *TokenMapping) GetChainDenom() string {
	if x != nil {
		return x.ChainDenom
	}
	return ""
}

func (x *TokenMapping) GetBaseDenom() string {
	if x != nil {
		return x.BaseDenom
	}
	return ""
}

func (x *TokenMapping) GetOriginChain() string {
	if x != nil {
		return x.OriginChain
	}
	return ""
}

func (x *TokenMapping) GetIsNative() bool {
	if x != nil {
		return x.IsNative
	}
	return false
}

type IBCLeg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromChain string        `protobuf:"bytes,1,opt,name=from_chain,proto3" json:"from_chain,omitempty"`
	ToChain   string        `protobuf:"bytes,2,opt,name=to_chain,proto3" json:"to_chain,omitempty"`
	Channel   string        `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Port      string        `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	Token     *TokenMapping `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Amount    string        `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *IBCLeg) Reset() {
	*x = IBCLeg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IBCLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IBCLeg) ProtoMessage() {}

func (x *IBCLeg) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IBCLeg.ProtoReflect.Descriptor instead.
func (*IBCLeg) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{1}
}

func (x *IBCLeg) GetFromChain() string {
	if x != nil {
		return x.FromChain
	}
	return ""
}

func (x *IBCLeg) GetToChain() string {
	if x != nil {
		return x.ToChain
	}
	return ""
}

func (x *IBCLeg) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *IBCLeg) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *IBCLeg) GetToken() *TokenMapping {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *IBCLeg) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// DirectRoute is a single IBC transfer directly between chain_from and
// chain_to, with no intermediate chains and no swap.
type DirectRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transfer *IBCLeg `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
}

func (x *DirectRoute) Reset() {
	*x = DirectRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectRoute) ProtoMessage() {}

func (x *DirectRoute) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectRoute.ProtoReflect.Descriptor instead.
func (*DirectRoute) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{2}
}

func (x *DirectRoute) GetTransfer() *IBCLeg {
	if x != nil {
		return x.Transfer
	}
	return nil
}

// IndirectRoute is a multi-hop IBC-only path with no swap involved - the
// token is simply forwarded through one or more intermediate chains.
type IndirectRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// All chain IDs in order, from chain_from to chain_to.
	Path []string `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	// One IBCLeg per hop, in order.
	Legs []*IBCLeg `protobuf:"bytes,2,rep,name=legs,proto3" json:"legs,omitempty"`
	// True if Packet Forward Middleware (PFM) can be used to chain the
	// hops from pfm_start_chain onward into a single MsgTransfer with a
	// forwarding memo, instead of the caller submitting one MsgTransfer
	// per hop.
	SupportsPfm bool `protobuf:"varint,3,opt,name=supports_pfm,proto3" json:"supports_pfm,omitempty"`
	// The first chain in the path from which PFM forwarding applies.
	// Only meaningful when supports_pfm is true.
	PfmStartChain string `protobuf:"bytes,4,opt,name=pfm_start_chain,proto3" json:"pfm_start_chain,omitempty"`
	// The PFM forward memo to attach to the MsgTransfer sent from
	// pfm_start_chain. Only populated when supports_pfm is true.
	PfmMemo string `protobuf:"bytes,5,opt,name=pfm_memo,proto3" json:"pfm_memo,omitempty"`
}

func (x *IndirectRoute) Reset() {
	*x = IndirectRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndirectRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndirectRoute) ProtoMessage() {}

func (x *IndirectRoute) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndirectRoute.ProtoReflect.Descriptor instead.
func (*IndirectRoute) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{3}
}

func (x *IndirectRoute) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *IndirectRoute) GetLegs() []*IBCLeg {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *IndirectRoute) GetSupportsPfm() bool {
	if x != nil {
		return x.SupportsPfm
	}
	return false
}

func (x *IndirectRoute) GetPfmStartChain() string {
	if x != nil {
		return x.PfmStartChain
	}
	return ""
}

func (x *IndirectRoute) GetPfmMemo() string {
	if x != nil {
		return x.PfmMemo
	}
	return ""
}

// BrokerSwapRoute represents a route involving a swap on a broker chain.
// Supports various scenarios:
// - Same-chain swap: inbound_leg absent, outbound_legs=[] (e.g., osmosis ATOM -> osmosis OSMO)
// - Swap from broker: inbound_leg absent (e.g., osmosis USDC -> juno JUNO)
// - Standard 3-chain: inbound_leg set, len(outbound_legs)=1
// - Multi-hop outbound: inbound_leg set, len(outbound_legs)>1 (e.g., cosmos ATOM -> swap -> noble -> juno)
type BrokerSwapRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// All chain IDs in order
	Path []string `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	// IBC transfer to reach broker (absent if starting from broker)
	InboundLegs []*IBCLeg `protobuf:"bytes,2,rep,name=inbound_legs,proto3" json:"inbound_legs,omitempty"`
	// The swap operation on the broker chain
	Swap *SwapQuote `protobuf:"bytes,3,opt,name=swap,proto3" json:"swap,omitempty"`
	// IBC transfers after swap (empty if destination is broker)
	// Can be multiple for multi-hop forwarding via PFM
	OutboundLegs []*IBCLeg `protobuf:"bytes,4,rep,name=outbound_legs,proto3" json:"outbound_legs,omitempty"`
	// Can use PFM for outbound legs
	OutboundSupportsPfm bool `protobuf:"varint,5,opt,name=outbound_supports_pfm,proto3" json:"outbound_supports_pfm,omitempty"`
	// Execution data for building transactions
	Execution *BrokerExecutionData `protobuf:"bytes,6,opt,name=execution,proto3" json:"execution,omitempty"`
}

func (x *BrokerSwapRoute) Reset() {
	*x = BrokerSwapRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokerSwapRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerSwapRoute) ProtoMessage() {}

func (x *BrokerSwapRoute) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerSwapRoute.ProtoReflect.Descriptor instead.
func (*BrokerSwapRoute) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{4}
}

func (x *BrokerSwapRoute) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *BrokerSwapRoute) GetInboundLegs() []*IBCLeg {
	if x != nil {
		return x.InboundLegs
	}
	return nil
}

func (x *BrokerSwapRoute) GetSwap() *SwapQuote {
	if x != nil {
		return x.Swap
	}
	return nil
}

func (x *BrokerSwapRoute) GetOutboundLegs() []*IBCLeg {
	if x != nil {
		return x.OutboundLegs
	}
	return nil
}

func (x *BrokerSwapRoute) GetOutboundSupportsPfm() bool {
	if x != nil {
		return x.OutboundSupportsPfm
	}
	return false
}

func (x *BrokerSwapRoute) GetExecution() *BrokerExecutionData {
	if x != nil {
		return x.Execution
	}
	return nil
}

// BrokerExecutionData contains ready-to-use transaction data. See
// docs/IBC_MEMO.md for how memo/smart_contract_data assemble into the
// ibc-hooks memo formats used to trigger the swap on the broker chain.
type BrokerExecutionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The IBC memo to use with MsgTransfer (contains wasm swap_and_action)
	Memo *string `protobuf:"bytes,1,opt,name=memo,proto3,oneof" json:"memo,omitempty"`
	// The smart contract data to use with the swap and transfer
	SmartContractData *WasmData `protobuf:"bytes,2,opt,name=smart_contract_data,proto3,oneof" json:"smart_contract_data,omitempty"`
	// Receiver address for MsgTransfer (the ibc-hooks contract)
	IbcReceiver *string `protobuf:"bytes,3,opt,name=ibc_receiver,proto3,oneof" json:"ibc_receiver,omitempty"`
	// Recovery address on broker chain (where funds go if swap/forward fails)
	RecoverAddress string `protobuf:"bytes,4,opt,name=recover_address,proto3" json:"recover_address,omitempty"`
	// Minimum output amount after slippage (1% default)
	MinOutputAmount string `protobuf:"bytes,5,opt,name=min_output_amount,proto3" json:"min_output_amount,omitempty"`
	// True if using wasm ibc-hooks (vs simple PFM)
	UsesWasm bool `protobuf:"varint,6,opt,name=uses_wasm,proto3" json:"uses_wasm,omitempty"`
	// Human-readable description
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *BrokerExecutionData) Reset() {
	*x = BrokerExecutionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrokerExecutionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerExecutionData) ProtoMessage() {}

func (x *BrokerExecutionData) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerExecutionData.ProtoReflect.Descriptor instead.
func (*BrokerExecutionData) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{5}
}

func (x *BrokerExecutionData) GetMemo() string {
	if x != nil && x.Memo != nil {
		return *x.Memo
	}
	return ""
}

func (x *BrokerExecutionData) GetSmartContractData() *WasmData {
	if x != nil {
		return x.SmartContractData
	}
	return nil
}

func (x *BrokerExecutionData) GetIbcReceiver() string {
	if x != nil && x.IbcReceiver != nil {
		return *x.IbcReceiver
	}
	return ""
}

func (x *BrokerExecutionData) GetRecoverAddress() string {
	if x != nil {
		return x.RecoverAddress
	}
	return ""
}

func (x *BrokerExecutionData) GetMinOutputAmount() string {
	if x != nil {
		return x.MinOutputAmount
	}
	return ""
}

func (x *BrokerExecutionData) GetUsesWasm() bool {
	if x != nil {
		return x.UsesWasm
	}
	return false
}

func (x *BrokerExecutionData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// SwapQuote with broker-specific route data
type SwapQuote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Broker       string        `protobuf:"bytes,1,opt,name=broker,proto3" json:"broker,omitempty"`
	TokenIn      *TokenMapping `protobuf:"bytes,2,opt,name=token_in,proto3" json:"token_in,omitempty"`
	TokenOut     *TokenMapping `protobuf:"bytes,3,opt,name=token_out,proto3" json:"token_out,omitempty"`
	AmountIn     string        `protobuf:"bytes,4,opt,name=amount_in,proto3" json:"amount_in,omitempty"`
	AmountOut    string        `protobuf:"bytes,5,opt,name=amount_out,proto3" json:"amount_out,omitempty"`
	PriceImpact  string        `protobuf:"bytes,6,opt,name=price_impact,proto3" json:"price_impact,omitempty"`
	EffectiveFee string        `protobuf:"bytes,7,opt,name=effective_fee,proto3" json:"effective_fee,omitempty"`
	// Broker-specific route data using oneof for type safety
	//
	// Types that are assignable to RouteData:
	//
	//	*SwapQuote_OsmosisRouteData
	RouteData isSwapQuote_RouteData `protobuf_oneof:"route_data"`
}

func (x *SwapQuote) Reset() {
	*x = SwapQuote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwapQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapQuote) ProtoMessage() {}

func (x *SwapQuote) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapQuote.ProtoReflect.Descriptor instead.
func (*SwapQuote) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{6}
}

func (x *SwapQuote) GetBroker() string {
	if x != nil {
		return x.Broker
	}
	return ""
}

func (x *SwapQuote) GetTokenIn() *TokenMapping {
	if x != nil {
		return x.TokenIn
	}
	return nil
}

func (x *SwapQuote) GetTokenOut() *TokenMapping {
	if x != nil {
		return x.TokenOut
	}
	return nil
}

func (x *SwapQuote) GetAmountIn() string {
	if x != nil {
		return x.AmountIn
	}
	return ""
}

func (x *SwapQuote) GetAmountOut() string {
	if x != nil {
		return x.AmountOut
	}
	return ""
}

func (x *SwapQuote) GetPriceImpact() string {
	if x != nil {
		return x.PriceImpact
	}
	return ""
}

func (x *SwapQuote) GetEffectiveFee() string {
	if x != nil {
		return x.EffectiveFee
	}
	return ""
}

func (m *SwapQuote) GetRouteData() isSwapQuote_RouteData {
	if m != nil {
		return m.RouteData
	}
	return nil
}

func (x *SwapQuote) GetOsmosisRouteData() *OsmosisRouteData {
	if x, ok := x.GetRouteData().(*SwapQuote_OsmosisRouteData); ok {
		return x.OsmosisRouteData
	}
	return nil
}

type isSwapQuote_RouteData interface {
	isSwapQuote_RouteData()
}

type SwapQuote_OsmosisRouteData struct {
	OsmosisRouteData *OsmosisRouteData `protobuf:"bytes,8,opt,name=osmosis_route_data,proto3,oneof"` // Future brokers can be added here without breaking existing clients
}

func (*SwapQuote_OsmosisRouteData) isSwapQuote_RouteData() {}

// Osmosis-specific route data (from SQS API)
type OsmosisRouteData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routes               []*OsmosisRoute `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	LiquidityCap         string          `protobuf:"bytes,2,opt,name=liquidity_cap,proto3" json:"liquidity_cap,omitempty"`
	LiquidityCapOverflow bool            `protobuf:"varint,3,opt,name=liquidity_cap_overflow,proto3" json:"liquidity_cap_overflow,omitempty"`
}

func (x *OsmosisRouteData) Reset() {
	*x = OsmosisRouteData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OsmosisRouteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsmosisRouteData) ProtoMessage() {}

func (x *OsmosisRouteData) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsmosisRouteData.ProtoReflect.Descriptor instead.
func (*OsmosisRouteData) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{7}
}

func (x *OsmosisRouteData) GetRoutes() []*OsmosisRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *OsmosisRouteData) GetLiquidityCap() string {
	if x != nil {
		return x.LiquidityCap
	}
	return ""
}

func (x *OsmosisRouteData) GetLiquidityCapOverflow() bool {
	if x != nil {
		return x.LiquidityCapOverflow
	}
	return false
}

type OsmosisRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pools     []*OsmosisPool `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
	HasCwPool bool           `protobuf:"varint,2,opt,name=has_cw_pool,proto3" json:"has_cw_pool,omitempty"`
	OutAmount string         `protobuf:"bytes,3,opt,name=out_amount,proto3" json:"out_amount,omitempty"`
	InAmount  string         `protobuf:"bytes,4,opt,name=in_amount,proto3" json:"in_amount,omitempty"`
}

func (x *OsmosisRoute) Reset() {
	*x = OsmosisRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OsmosisRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsmosisRoute) ProtoMessage() {}

func (x *OsmosisRoute) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsmosisRoute.ProtoReflect.Descriptor instead.
func (*OsmosisRoute) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{8}
}

func (x *OsmosisRoute) GetPools() []*OsmosisPool {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *OsmosisRoute) GetHasCwPool() bool {
	if x != nil {
		return x.HasCwPool
	}
	return false
}

func (x *OsmosisRoute) GetOutAmount() string {
	if x != nil {
		return x.OutAmount
	}
	return ""
}

func (x *OsmosisRoute) GetInAmount() string {
	if x != nil {
		return x.InAmount
	}
	return ""
}

type OsmosisPool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          int32  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	SpreadFactor  string `protobuf:"bytes,3,opt,name=spread_factor,proto3" json:"spread_factor,omitempty"`
	TokenOutDenom string `protobuf:"bytes,4,opt,name=token_out_denom,proto3" json:"token_out_denom,omitempty"`
	TakerFee      string `protobuf:"bytes,5,opt,name=taker_fee,proto3" json:"taker_fee,omitempty"`
	LiquidityCap  string `protobuf:"bytes,6,opt,name=liquidity_cap,proto3" json:"liquidity_cap,omitempty"`
}

func (x *OsmosisPool) Reset() {
	*x = OsmosisPool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OsmosisPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsmosisPool) ProtoMessage() {}

func (x *OsmosisPool) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsmosisPool.ProtoReflect.Descriptor instead.
func (*OsmosisPool) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{9}
}

func (x *OsmosisPool) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OsmosisPool) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *OsmosisPool) GetSpreadFactor() string {
	if x != nil {
		return x.SpreadFactor
	}
	return ""
}

func (x *OsmosisPool) GetTokenOutDenom() string {
	if x != nil {
		return x.TokenOutDenom
	}
	return ""
}

func (x *OsmosisPool) GetTakerFee() string {
	if x != nil {
		return x.TakerFee
	}
	return ""
}

func (x *OsmosisPool) GetLiquidityCap() string {
	if x != nil {
		return x.LiquidityCap
	}
	return ""
}

type WasmData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contract string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Msg      *WasmMsg `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *WasmData) Reset() {
	*x = WasmData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WasmData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmData) ProtoMessage() {}

func (x *WasmData) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmData.ProtoReflect.Descriptor instead.
func (*WasmData) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{10}
}

func (x *WasmData) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *WasmData) GetMsg() *WasmMsg {
	if x != nil {
		return x.Msg
	}
	return nil
}

type WasmMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SwapAndAction *SwapAndAction `protobuf:"bytes,1,opt,name=swap_and_action,proto3" json:"swap_and_action,omitempty"`
}

func (x *WasmMsg) Reset() {
	*x = WasmMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WasmMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmMsg) ProtoMessage() {}

func (x *WasmMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmMsg.ProtoReflect.Descriptor instead.
func (*WasmMsg) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{11}
}

func (x *WasmMsg) GetSwapAndAction() *SwapAndAction {
	if x != nil {
		return x.SwapAndAction
	}
	return nil
}

type SwapAndAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// SwapAndAction is the entry point contract message structure
	UserSwap         *UserSwap       `protobuf:"bytes,1,opt,name=user_swap,proto3" json:"user_swap,omitempty"`
	MinAsset         *MinAsset       `protobuf:"bytes,2,opt,name=min_asset,proto3" json:"min_asset,omitempty"`
	TimeoutTimestamp int64           `protobuf:"varint,3,opt,name=timeout_timestamp,proto3" json:"timeout_timestamp,omitempty"`
	PostSwapAction   *PostSwapAction `protobuf:"bytes,4,opt,name=post_swap_action,proto3" json:"post_swap_action,omitempty"`
	Affiliates       []string        `protobuf:"bytes,5,rep,name=affiliates,proto3" json:"affiliates,omitempty"`
}

func (x *SwapAndAction) Reset() {
	*x = SwapAndAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwapAndAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapAndAction) ProtoMessage() {}

func (x *SwapAndAction) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapAndAction.ProtoReflect.Descriptor instead.
func (*SwapAndAction) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{12}
}

func (x *SwapAndAction) GetUserSwap() *UserSwap {
	if x != nil {
		return x.UserSwap
	}
	return nil
}

func (x *SwapAndAction) GetMinAsset() *MinAsset {
	if x != nil {
		return x.MinAsset
	}
	return nil
}

func (x *SwapAndAction) GetTimeoutTimestamp() int64 {
	if x != nil {
		return x.TimeoutTimestamp
	}
	return 0
}

func (x *SwapAndAction) GetPostSwapAction() *PostSwapAction {
	if x != nil {
		return x.PostSwapAction
	}
	return nil
}

func (x *SwapAndAction) GetAffiliates() []string {
	if x != nil {
		return x.Affiliates
	}
	return nil
}

type SwapExactAssetIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SwapVenueName string           `protobuf:"bytes,1,opt,name=swap_venue_name,proto3" json:"swap_venue_name,omitempty"`
	Operations    []*SwapOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
}

func (x *SwapExactAssetIn) Reset() {
	*x = SwapExactAssetIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwapExactAssetIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapExactAssetIn) ProtoMessage() {}

func (x *SwapExactAssetIn) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapExactAssetIn.ProtoReflect.Descriptor instead.
func (*SwapExactAssetIn) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{13}
}

func (x *SwapExactAssetIn) GetSwapVenueName() string {
	if x != nil {
		return x.SwapVenueName
	}
	return ""
}

func (x *SwapExactAssetIn) GetOperations() []*SwapOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type SwapOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pool     string `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	DenomIn  string `protobuf:"bytes,2,opt,name=denom_in,proto3" json:"denom_in,omitempty"`
	DenomOut string `protobuf:"bytes,3,opt,name=denom_out,proto3" json:"denom_out,omitempty"`
	// Interface is used by some DEXs (like Injective), optional
	Interface *string `protobuf:"bytes,4,opt,name=interface,proto3,oneof" json:"interface,omitempty"`
}

func (x *SwapOperation) Reset() {
	*x = SwapOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwapOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapOperation) ProtoMessage() {}

func (x *SwapOperation) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapOperation.ProtoReflect.Descriptor instead.
func (*SwapOperation) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{14}
}

func (x *SwapOperation) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *SwapOperation) GetDenomIn() string {
	if x != nil {
		return x.DenomIn
	}
	return ""
}

func (x *SwapOperation) GetDenomOut() string {
	if x != nil {
		return x.DenomOut
	}
	return ""
}

func (x *SwapOperation) GetInterface() string {
	if x != nil && x.Interface != nil {
		return *x.Interface
	}
	return ""
}

type MinAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Native *Asset `protobuf:"bytes,1,opt,name=native,proto3" json:"native,omitempty"`
}

func (x *MinAsset) Reset() {
	*x = MinAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinAsset) ProtoMessage() {}

func (x *MinAsset) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinAsset.ProtoReflect.Descriptor instead.
func (*MinAsset) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{15}
}

func (x *MinAsset) GetNative() *Asset {
	if x != nil {
		return x.Native
	}
	return nil
}

type Asset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Denom  string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (x *Asset) Reset() {
	*x = Asset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{16}
}

func (x *Asset) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Asset) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

type PostSwapAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Action:
	//
	//	*PostSwapAction_IbcTransfer
	//	*PostSwapAction_Transfer
	Action isPostSwapAction_Action `protobuf_oneof:"action"`
}

func (x *PostSwapAction) Reset() {
	*x = PostSwapAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostSwapAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostSwapAction) ProtoMessage() {}

func (x *PostSwapAction) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostSwapAction.ProtoReflect.Descriptor instead.
func (*PostSwapAction) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{17}
}

func (m *PostSwapAction) GetAction() isPostSwapAction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *PostSwapAction) GetIbcTransfer() *IBCTransfer {
	if x, ok := x.GetAction().(*PostSwapAction_IbcTransfer); ok {
		return x.IbcTransfer
	}
	return nil
}

func (x *PostSwapAction) GetTransfer() *Transfer {
	if x, ok := x.GetAction().(*PostSwapAction_Transfer); ok {
		return x.Transfer
	}
	return nil
}

type isPostSwapAction_Action interface {
	isPostSwapAction_Action()
}

type PostSwapAction_IbcTransfer struct {
	IbcTransfer *IBCTransfer `protobuf:"bytes,1,opt,name=ibc_transfer,proto3,oneof"`
}

type PostSwapAction_Transfer struct {
	Transfer *Transfer `protobuf:"bytes,2,opt,name=transfer,proto3,oneof"`
}

func (*PostSwapAction_IbcTransfer) isPostSwapAction_Action() {}

func (*PostSwapAction_Transfer) isPostSwapAction_Action() {}

type IBCTransfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IbcInfo *IBCInfo `protobuf:"bytes,1,opt,name=ibc_info,proto3" json:"ibc_info,omitempty"`
}

func (x *IBCTransfer) Reset() {
	*x = IBCTransfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IBCTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IBCTransfer) ProtoMessage() {}

func (x *IBCTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IBCTransfer.ProtoReflect.Descriptor instead.
func (*IBCTransfer) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{18}
}

func (x *IBCTransfer) GetIbcInfo() *IBCInfo {
	if x != nil {
		return x.IbcInfo
	}
	return nil
}

type Transfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToAddress string `protobuf:"bytes,1,opt,name=to_address,proto3" json:"to_address,omitempty"`
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{19}
}

func (x *Transfer) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

type IBCInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memo           string `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	Receiver       string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	RecoverAddress string `protobuf:"bytes,3,opt,name=recover_address,proto3" json:"recover_address,omitempty"`
	SourceChannel  string `protobuf:"bytes,4,opt,name=source_channel,proto3" json:"source_channel,omitempty"`
}

func (x *IBCInfo) Reset() {
	*x = IBCInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IBCInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IBCInfo) ProtoMessage() {}

func (x *IBCInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IBCInfo.ProtoReflect.Descriptor instead.
func (*IBCInfo) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{20}
}

func (x *IBCInfo) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *IBCInfo) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *IBCInfo) GetRecoverAddress() string {
	if x != nil {
		return x.RecoverAddress
	}
	return ""
}

func (x *IBCInfo) GetSourceChannel() string {
	if x != nil {
		return x.SourceChannel
	}
	return ""
}

type UserSwap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SwapExactAssetIn *SwapExactAssetIn `protobuf:"bytes,1,opt,name=swap_exact_asset_in,proto3" json:"swap_exact_asset_in,omitempty"`
}

func (x *UserSwap) Reset() {
	*x = UserSwap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSwap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSwap) ProtoMessage() {}

func (x *UserSwap) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSwap.ProtoReflect.Descriptor instead.
func (*UserSwap) Descriptor() ([]byte, []int) {
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP(), []int{21}
}

func (x *UserSwap) GetSwapExactAssetIn() *SwapExactAssetIn {
	if x != nil {
		return x.SwapExactAssetIn
	}
	return nil
}

var File_pathfinder_v2beta_pathfinder_v2beta_common_proto protoreflect.FileDescriptor

var file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDesc = []byte{
	0x0a, 0x30, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x32, 0x62,
	0x65, 0x74, 0x61, 0x2f, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x76,
	0x32, 0x62, 0x65, 0x74, 0x61, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x11, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76,
	0x32, 0x62, 0x65, 0x74, 0x61, 0x22, 0x92, 0x01, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4d,
	0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f,
	0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x5f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65,
	0x5f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61,
	0x73, 0x65, 0x5f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x69, 0x73, 0x5f, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x69, 0x73, 0x5f, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x22, 0xc1, 0x01, 0x0a, 0x06, 0x49,
	0x42, 0x43, 0x4c, 0x65, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x5f,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x35, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65,
	0x74, 0x61, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x44,
	0x0a, 0x0b, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x35, 0x0a,
	0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62,
	0x65, 0x74, 0x61, 0x2e, 0x49, 0x42, 0x43, 0x4c, 0x65, 0x67, 0x52, 0x08, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x22, 0xbc, 0x01, 0x0a, 0x0d, 0x49, 0x6e, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x2d, 0x0a, 0x04, 0x6c, 0x65,
	0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x49, 0x42, 0x43,
	0x4c, 0x65, 0x67, 0x52, 0x04, 0x6c, 0x65, 0x67, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f, 0x70, 0x66, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0c, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f, 0x70, 0x66, 0x6d, 0x12, 0x28, 0x0a,
	0x0f, 0x70, 0x66, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x66, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x66, 0x6d, 0x5f, 0x6d,
	0x65, 0x6d, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x66, 0x6d, 0x5f, 0x6d,
	0x65, 0x6d, 0x6f, 0x22, 0xd3, 0x02, 0x0a, 0x0f, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x53, 0x77,
	0x61, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x3d, 0x0a, 0x0c, 0x69,
	0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x6c, 0x65, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76,
	0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x49, 0x42, 0x43, 0x4c, 0x65, 0x67, 0x52, 0x0c, 0x69, 0x6e,
	0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x6c, 0x65, 0x67, 0x73, 0x12, 0x30, 0x0a, 0x04, 0x73, 0x77,
	0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x77, 0x61,
	0x70, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x04, 0x73, 0x77, 0x61, 0x70, 0x12, 0x3f, 0x0a, 0x0d,
	0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x6c, 0x65, 0x67, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x49, 0x42, 0x43, 0x4c, 0x65, 0x67, 0x52, 0x0d,
	0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x6c, 0x65, 0x67, 0x73, 0x12, 0x34, 0x0a,
	0x15, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x5f, 0x70, 0x66, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x6f, 0x75,
	0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f,
	0x70, 0x66, 0x6d, 0x12, 0x44, 0x0a, 0x09, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x42, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09,
	0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xf5, 0x02, 0x0a, 0x13, 0x42, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x17, 0x0a, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x52, 0x0a, 0x13, 0x73, 0x6d,
	0x61, 0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x57, 0x61, 0x73, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x48, 0x01, 0x52, 0x13, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x12, 0x27,
	0x0a, 0x0c, 0x69, 0x62, 0x63, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0c, 0x69, 0x62, 0x63, 0x5f, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x2c, 0x0a, 0x11, 0x6d, 0x69, 0x6e, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6d, 0x69,
	0x6e, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x73, 0x5f, 0x77, 0x61, 0x73, 0x6d, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x75, 0x73, 0x65, 0x73, 0x5f, 0x77, 0x61, 0x73, 0x6d, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x73, 0x6d, 0x61,
	0x72, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x69, 0x62, 0x63, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x22, 0x8c, 0x03, 0x0a, 0x09, 0x53, 0x77, 0x61, 0x70, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x61, 0x74, 0x68,
	0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x69, 0x6e, 0x12, 0x3d, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6f, 0x75,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f,
	0x6f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6f, 0x75, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6f, 0x75,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6d, 0x70, 0x61, 0x63,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x69,
	0x6d, 0x70, 0x61, 0x63, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x12, 0x55, 0x0a, 0x12, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x69, 0x73, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x4f, 0x73, 0x6d, 0x6f,
	0x73, 0x69, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x12,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x69, 0x73, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x42, 0x0c, 0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x22, 0xa9, 0x01, 0x0a, 0x10, 0x4f, 0x73, 0x6d, 0x6f, 0x73, 0x69, 0x73, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x4f, 0x73, 0x6d, 0x6f, 0x73, 0x69,
	0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x24,
	0x0a, 0x0d, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x61, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x5f, 0x63, 0x61, 0x70, 0x12, 0x36, 0x0a, 0x16, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74,
	0x79, 0x5f, 0x63, 0x61, 0x70, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f,
	0x63, 0x61, 0x70, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x22, 0xa4, 0x01, 0x0a,
	0x0c, 0x4f, 0x73, 0x6d, 0x6f, 0x73, 0x69, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x34, 0x0a,
	0x05, 0x70, 0x6f, 0x6f, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70,
	0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61,
	0x2e, 0x4f, 0x73, 0x6d, 0x6f, 0x73, 0x69, 0x73, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x05, 0x70, 0x6f,
	0x6f, 0x6c, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x61, 0x73, 0x5f, 0x63, 0x77, 0x5f, 0x70, 0x6f,
	0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x5f, 0x63, 0x77,
	0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x75, 0x74, 0x5f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x5f, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0xc5, 0x01, 0x0a, 0x0b, 0x4f, 0x73, 0x6d, 0x6f, 0x73, 0x69, 0x73, 0x50,
	0x6f, 0x6f, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x70, 0x72, 0x65, 0x61,
	0x64, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x73, 0x70, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x28, 0x0a,
	0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6f, 0x75, 0x74, 0x5f, 0x64, 0x65, 0x6e, 0x6f, 0x6d,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x6f, 0x75,
	0x74, 0x5f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x61, 0x6b, 0x65, 0x72,
	0x5f, 0x66, 0x65, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x6b, 0x65,
	0x72, 0x5f, 0x66, 0x65, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69,
	0x74, 0x79, 0x5f, 0x63, 0x61, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x69,
	0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x61, 0x70, 0x22, 0x54, 0x0a, 0x08, 0x57,
	0x61, 0x73, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x12, 0x2c, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32,
	0x62, 0x65, 0x74, 0x61, 0x2e, 0x57, 0x61, 0x73, 0x6d, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x55, 0x0a, 0x07, 0x57, 0x61, 0x73, 0x6d, 0x4d, 0x73, 0x67, 0x12, 0x4a, 0x0a, 0x0f,
	0x73, 0x77, 0x61, 0x70, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x41, 0x6e,
	0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x73, 0x77, 0x61, 0x70, 0x5f, 0x61, 0x6e,
	0x64, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa2, 0x02, 0x0a, 0x0d, 0x53, 0x77, 0x61,
	0x70, 0x41, 0x6e, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x77, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74,
	0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x77, 0x61, 0x70, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x73, 0x77, 0x61, 0x70, 0x12, 0x39, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x4d, 0x69, 0x6e,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x12, 0x2c, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x4d,
	0x0a, 0x10, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x77, 0x61, 0x70, 0x5f, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x53, 0x77, 0x61, 0x70, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x70, 0x6f, 0x73,
	0x74, 0x5f, 0x73, 0x77, 0x61, 0x70, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x61, 0x66, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x61, 0x66, 0x66, 0x69, 0x6c, 0x69, 0x61, 0x74, 0x65, 0x73, 0x22, 0x7e, 0x0a,
	0x10, 0x53, 0x77, 0x61, 0x70, 0x45, 0x78, 0x61, 0x63, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x49,
	0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x77, 0x61, 0x70, 0x5f, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x77, 0x61, 0x70,
	0x5f, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62,
	0x65, 0x74, 0x61, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x8e, 0x01,
	0x0a, 0x0d, 0x53, 0x77, 0x61, 0x70, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x6f, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x5f, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x5f, 0x6f, 0x75, 0x74, 0x12, 0x21, 0x0a,
	0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x88, 0x01, 0x01,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x22, 0x3c,
	0x0a, 0x08, 0x4d, 0x69, 0x6e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x6e, 0x61,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x61, 0x74,
	0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x52, 0x06, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x22, 0x35, 0x0a, 0x05,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65,
	0x6e, 0x6f, 0x6d, 0x22, 0x9b, 0x01, 0x0a, 0x0e, 0x50, 0x6f, 0x73, 0x74, 0x53, 0x77, 0x61, 0x70,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x44, 0x0a, 0x0c, 0x69, 0x62, 0x63, 0x5f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70,
	0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61,
	0x2e, 0x49, 0x42, 0x43, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0c,
	0x69, 0x62, 0x63, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x08,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65,
	0x74, 0x61, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x45, 0x0a, 0x0b, 0x49, 0x42, 0x43, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x12, 0x36, 0x0a, 0x08, 0x69, 0x62, 0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e,
	0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x49, 0x42, 0x43, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x69, 0x62, 0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x2a, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x07, 0x49, 0x42, 0x43, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6d, 0x65, 0x6d, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x22, 0x61, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x53, 0x77, 0x61, 0x70, 0x12, 0x55,
	0x0a, 0x13, 0x73, 0x77, 0x61, 0x70, 0x5f, 0x65, 0x78, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x5f, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x61,
	0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x2e,
	0x53, 0x77, 0x61, 0x70, 0x45, 0x78, 0x61, 0x63, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x49, 0x6e,
	0x52, 0x13, 0x73, 0x77, 0x61, 0x70, 0x5f, 0x65, 0x78, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x5f, 0x69, 0x6e, 0x42, 0x58, 0x5a, 0x56, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x6f, 0x67, 0x77, 0x68, 0x65, 0x65, 0x6c, 0x2d, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x72, 0x61, 0x2d, 0x70,
	0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2f, 0x70, 0x61, 0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x61,
	0x74, 0x68, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x32, 0x62, 0x65, 0x74, 0x61, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescOnce sync.Once
	file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescData = file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDesc
)

func file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescGZIP() []byte {
	file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescOnce.Do(func() {
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescData)
	})
	return file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDescData
}

var file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pathfinder_v2beta_pathfinder_v2beta_common_proto_goTypes = []any{
	(*TokenMapping)(nil),        // 0: pathfinder.v2beta.TokenMapping
	(*IBCLeg)(nil),              // 1: pathfinder.v2beta.IBCLeg
	(*DirectRoute)(nil),         // 2: pathfinder.v2beta.DirectRoute
	(*IndirectRoute)(nil),       // 3: pathfinder.v2beta.IndirectRoute
	(*BrokerSwapRoute)(nil),     // 4: pathfinder.v2beta.BrokerSwapRoute
	(*BrokerExecutionData)(nil), // 5: pathfinder.v2beta.BrokerExecutionData
	(*SwapQuote)(nil),           // 6: pathfinder.v2beta.SwapQuote
	(*OsmosisRouteData)(nil),    // 7: pathfinder.v2beta.OsmosisRouteData
	(*OsmosisRoute)(nil),        // 8: pathfinder.v2beta.OsmosisRoute
	(*OsmosisPool)(nil),         // 9: pathfinder.v2beta.OsmosisPool
	(*WasmData)(nil),            // 10: pathfinder.v2beta.WasmData
	(*WasmMsg)(nil),             // 11: pathfinder.v2beta.WasmMsg
	(*SwapAndAction)(nil),       // 12: pathfinder.v2beta.SwapAndAction
	(*SwapExactAssetIn)(nil),    // 13: pathfinder.v2beta.SwapExactAssetIn
	(*SwapOperation)(nil),       // 14: pathfinder.v2beta.SwapOperation
	(*MinAsset)(nil),            // 15: pathfinder.v2beta.MinAsset
	(*Asset)(nil),               // 16: pathfinder.v2beta.Asset
	(*PostSwapAction)(nil),      // 17: pathfinder.v2beta.PostSwapAction
	(*IBCTransfer)(nil),         // 18: pathfinder.v2beta.IBCTransfer
	(*Transfer)(nil),            // 19: pathfinder.v2beta.Transfer
	(*IBCInfo)(nil),             // 20: pathfinder.v2beta.IBCInfo
	(*UserSwap)(nil),            // 21: pathfinder.v2beta.UserSwap
}
var file_pathfinder_v2beta_pathfinder_v2beta_common_proto_depIdxs = []int32{
	0,  // 0: pathfinder.v2beta.IBCLeg.token:type_name -> pathfinder.v2beta.TokenMapping
	1,  // 1: pathfinder.v2beta.DirectRoute.transfer:type_name -> pathfinder.v2beta.IBCLeg
	1,  // 2: pathfinder.v2beta.IndirectRoute.legs:type_name -> pathfinder.v2beta.IBCLeg
	1,  // 3: pathfinder.v2beta.BrokerSwapRoute.inbound_legs:type_name -> pathfinder.v2beta.IBCLeg
	6,  // 4: pathfinder.v2beta.BrokerSwapRoute.swap:type_name -> pathfinder.v2beta.SwapQuote
	1,  // 5: pathfinder.v2beta.BrokerSwapRoute.outbound_legs:type_name -> pathfinder.v2beta.IBCLeg
	5,  // 6: pathfinder.v2beta.BrokerSwapRoute.execution:type_name -> pathfinder.v2beta.BrokerExecutionData
	10, // 7: pathfinder.v2beta.BrokerExecutionData.smart_contract_data:type_name -> pathfinder.v2beta.WasmData
	0,  // 8: pathfinder.v2beta.SwapQuote.token_in:type_name -> pathfinder.v2beta.TokenMapping
	0,  // 9: pathfinder.v2beta.SwapQuote.token_out:type_name -> pathfinder.v2beta.TokenMapping
	7,  // 10: pathfinder.v2beta.SwapQuote.osmosis_route_data:type_name -> pathfinder.v2beta.OsmosisRouteData
	8,  // 11: pathfinder.v2beta.OsmosisRouteData.routes:type_name -> pathfinder.v2beta.OsmosisRoute
	9,  // 12: pathfinder.v2beta.OsmosisRoute.pools:type_name -> pathfinder.v2beta.OsmosisPool
	11, // 13: pathfinder.v2beta.WasmData.msg:type_name -> pathfinder.v2beta.WasmMsg
	12, // 14: pathfinder.v2beta.WasmMsg.swap_and_action:type_name -> pathfinder.v2beta.SwapAndAction
	21, // 15: pathfinder.v2beta.SwapAndAction.user_swap:type_name -> pathfinder.v2beta.UserSwap
	15, // 16: pathfinder.v2beta.SwapAndAction.min_asset:type_name -> pathfinder.v2beta.MinAsset
	17, // 17: pathfinder.v2beta.SwapAndAction.post_swap_action:type_name -> pathfinder.v2beta.PostSwapAction
	14, // 18: pathfinder.v2beta.SwapExactAssetIn.operations:type_name -> pathfinder.v2beta.SwapOperation
	16, // 19: pathfinder.v2beta.MinAsset.native:type_name -> pathfinder.v2beta.Asset
	18, // 20: pathfinder.v2beta.PostSwapAction.ibc_transfer:type_name -> pathfinder.v2beta.IBCTransfer
	19, // 21: pathfinder.v2beta.PostSwapAction.transfer:type_name -> pathfinder.v2beta.Transfer
	20, // 22: pathfinder.v2beta.IBCTransfer.ibc_info:type_name -> pathfinder.v2beta.IBCInfo
	13, // 23: pathfinder.v2beta.UserSwap.swap_exact_asset_in:type_name -> pathfinder.v2beta.SwapExactAssetIn
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_pathfinder_v2beta_pathfinder_v2beta_common_proto_init() }
func file_pathfinder_v2beta_pathfinder_v2beta_common_proto_init() {
	if File_pathfinder_v2beta_pathfinder_v2beta_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TokenMapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IBCLeg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DirectRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*IndirectRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BrokerSwapRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*BrokerExecutionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SwapQuote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*OsmosisRouteData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*OsmosisRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*OsmosisPool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*WasmData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*WasmMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*SwapAndAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*SwapExactAssetIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*SwapOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*MinAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*Asset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*PostSwapAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*IBCTransfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*Transfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*IBCInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*UserSwap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[5].OneofWrappers = []any{}
	file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[6].OneofWrappers = []any{
		(*SwapQuote_OsmosisRouteData)(nil),
	}
	file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[14].OneofWrappers = []any{}
	file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes[17].OneofWrappers = []any{
		(*PostSwapAction_IbcTransfer)(nil),
		(*PostSwapAction_Transfer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pathfinder_v2beta_pathfinder_v2beta_common_proto_goTypes,
		DependencyIndexes: file_pathfinder_v2beta_pathfinder_v2beta_common_proto_depIdxs,
		MessageInfos:      file_pathfinder_v2beta_pathfinder_v2beta_common_proto_msgTypes,
	}.Build()
	File_pathfinder_v2beta_pathfinder_v2beta_common_proto = out.File
	file_pathfinder_v2beta_pathfinder_v2beta_common_proto_rawDesc = nil
	file_pathfinder_v2beta_pathfinder_v2beta_common_proto_goTypes = nil
	file_pathfinder_v2beta_pathfinder_v2beta_common_proto_depIdxs = nil
}
