// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pathfinder/v2beta/pathfinder_v2beta_query.proto

package v2betaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2beta "github.com/Cogwheel-Validator/spectra-portal/pathfinder/rpc/services/pathfinder/v2beta"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PathfinderQueryServiceName is the fully-qualified name of the PathfinderQueryService service.
	PathfinderQueryServiceName = "pathfinder.v2beta.PathfinderQueryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PathfinderQueryServiceLookupDenomProcedure is the fully-qualified name of the
	// PathfinderQueryService's LookupDenom RPC.
	PathfinderQueryServiceLookupDenomProcedure = "/pathfinder.v2beta.PathfinderQueryService/LookupDenom"
	// PathfinderQueryServiceGetTokenDenomsProcedure is the fully-qualified name of the
	// PathfinderQueryService's GetTokenDenoms RPC.
	PathfinderQueryServiceGetTokenDenomsProcedure = "/pathfinder.v2beta.PathfinderQueryService/GetTokenDenoms"
	// PathfinderQueryServiceGetChainInfoProcedure is the fully-qualified name of the
	// PathfinderQueryService's GetChainInfo RPC.
	PathfinderQueryServiceGetChainInfoProcedure = "/pathfinder.v2beta.PathfinderQueryService/GetChainInfo"
	// PathfinderQueryServiceListSupportedChainsProcedure is the fully-qualified name of the
	// PathfinderQueryService's ListSupportedChains RPC.
	PathfinderQueryServiceListSupportedChainsProcedure = "/pathfinder.v2beta.PathfinderQueryService/ListSupportedChains"
	// PathfinderQueryServiceGetChainTokensProcedure is the fully-qualified name of the
	// PathfinderQueryService's GetChainTokens RPC.
	PathfinderQueryServiceGetChainTokensProcedure = "/pathfinder.v2beta.PathfinderQueryService/GetChainTokens"
)

// PathfinderQueryServiceClient is a client for the pathfinder.v2beta.PathfinderQueryService
// service.
type PathfinderQueryServiceClient interface {
	// LookupDenom resolves denom information on a specific chain
	// Accepts human-readable base denoms or IBC denom hashes
	LookupDenom(context.Context, *connect.Request[v2beta.LookupDenomRequest]) (*connect.Response[v2beta.LookupDenomResponse], error)
	// GetTokenDenoms returns all IBC denoms for a token across supported chains
	// Use this to discover what denom a token has on different chains
	GetTokenDenoms(context.Context, *connect.Request[v2beta.GetTokenDenomsRequest]) (*connect.Response[v2beta.GetTokenDenomsResponse], error)
	// GetChainInfo returns information about a specific chain
	GetChainInfo(context.Context, *connect.Request[v2beta.GetChainInfoRequest]) (*connect.Response[v2beta.GetChainInfoResponse], error)
	// ListSupportedChains returns a list of supported chains
	ListSupportedChains(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v2beta.ListSupportedChainsResponse], error)
	// GetChainTokens returns all tokens available on a specific chain
	// Includes both native tokens and IBC tokens with their denoms
	GetChainTokens(context.Context, *connect.Request[v2beta.GetChainTokensRequest]) (*connect.Response[v2beta.GetChainTokensResponse], error)
}

// NewPathfinderQueryServiceClient constructs a client for the
// pathfinder.v2beta.PathfinderQueryService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPathfinderQueryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PathfinderQueryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pathfinderQueryServiceMethods := v2beta.File_pathfinder_v2beta_pathfinder_v2beta_query_proto.Services().ByName("PathfinderQueryService").Methods()
	return &pathfinderQueryServiceClient{
		lookupDenom: connect.NewClient[v2beta.LookupDenomRequest, v2beta.LookupDenomResponse](
			httpClient,
			baseURL+PathfinderQueryServiceLookupDenomProcedure,
			connect.WithSchema(pathfinderQueryServiceMethods.ByName("LookupDenom")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getTokenDenoms: connect.NewClient[v2beta.GetTokenDenomsRequest, v2beta.GetTokenDenomsResponse](
			httpClient,
			baseURL+PathfinderQueryServiceGetTokenDenomsProcedure,
			connect.WithSchema(pathfinderQueryServiceMethods.ByName("GetTokenDenoms")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getChainInfo: connect.NewClient[v2beta.GetChainInfoRequest, v2beta.GetChainInfoResponse](
			httpClient,
			baseURL+PathfinderQueryServiceGetChainInfoProcedure,
			connect.WithSchema(pathfinderQueryServiceMethods.ByName("GetChainInfo")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listSupportedChains: connect.NewClient[emptypb.Empty, v2beta.ListSupportedChainsResponse](
			httpClient,
			baseURL+PathfinderQueryServiceListSupportedChainsProcedure,
			connect.WithSchema(pathfinderQueryServiceMethods.ByName("ListSupportedChains")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getChainTokens: connect.NewClient[v2beta.GetChainTokensRequest, v2beta.GetChainTokensResponse](
			httpClient,
			baseURL+PathfinderQueryServiceGetChainTokensProcedure,
			connect.WithSchema(pathfinderQueryServiceMethods.ByName("GetChainTokens")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// pathfinderQueryServiceClient implements PathfinderQueryServiceClient.
type pathfinderQueryServiceClient struct {
	lookupDenom         *connect.Client[v2beta.LookupDenomRequest, v2beta.LookupDenomResponse]
	getTokenDenoms      *connect.Client[v2beta.GetTokenDenomsRequest, v2beta.GetTokenDenomsResponse]
	getChainInfo        *connect.Client[v2beta.GetChainInfoRequest, v2beta.GetChainInfoResponse]
	listSupportedChains *connect.Client[emptypb.Empty, v2beta.ListSupportedChainsResponse]
	getChainTokens      *connect.Client[v2beta.GetChainTokensRequest, v2beta.GetChainTokensResponse]
}

// LookupDenom calls pathfinder.v2beta.PathfinderQueryService.LookupDenom.
func (c *pathfinderQueryServiceClient) LookupDenom(ctx context.Context, req *connect.Request[v2beta.LookupDenomRequest]) (*connect.Response[v2beta.LookupDenomResponse], error) {
	return c.lookupDenom.CallUnary(ctx, req)
}

// GetTokenDenoms calls pathfinder.v2beta.PathfinderQueryService.GetTokenDenoms.
func (c *pathfinderQueryServiceClient) GetTokenDenoms(ctx context.Context, req *connect.Request[v2beta.GetTokenDenomsRequest]) (*connect.Response[v2beta.GetTokenDenomsResponse], error) {
	return c.getTokenDenoms.CallUnary(ctx, req)
}

// GetChainInfo calls pathfinder.v2beta.PathfinderQueryService.GetChainInfo.
func (c *pathfinderQueryServiceClient) GetChainInfo(ctx context.Context, req *connect.Request[v2beta.GetChainInfoRequest]) (*connect.Response[v2beta.GetChainInfoResponse], error) {
	return c.getChainInfo.CallUnary(ctx, req)
}

// ListSupportedChains calls pathfinder.v2beta.PathfinderQueryService.ListSupportedChains.
func (c *pathfinderQueryServiceClient) ListSupportedChains(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v2beta.ListSupportedChainsResponse], error) {
	return c.listSupportedChains.CallUnary(ctx, req)
}

// GetChainTokens calls pathfinder.v2beta.PathfinderQueryService.GetChainTokens.
func (c *pathfinderQueryServiceClient) GetChainTokens(ctx context.Context, req *connect.Request[v2beta.GetChainTokensRequest]) (*connect.Response[v2beta.GetChainTokensResponse], error) {
	return c.getChainTokens.CallUnary(ctx, req)
}

// PathfinderQueryServiceHandler is an implementation of the
// pathfinder.v2beta.PathfinderQueryService service.
type PathfinderQueryServiceHandler interface {
	// LookupDenom resolves denom information on a specific chain
	// Accepts human-readable base denoms or IBC denom hashes
	LookupDenom(context.Context, *connect.Request[v2beta.LookupDenomRequest]) (*connect.Response[v2beta.LookupDenomResponse], error)
	// GetTokenDenoms returns all IBC denoms for a token across supported chains
	// Use this to discover what denom a token has on different chains
	GetTokenDenoms(context.Context, *connect.Request[v2beta.GetTokenDenomsRequest]) (*connect.Response[v2beta.GetTokenDenomsResponse], error)
	// GetChainInfo returns information about a specific chain
	GetChainInfo(context.Context, *connect.Request[v2beta.GetChainInfoRequest]) (*connect.Response[v2beta.GetChainInfoResponse], error)
	// ListSupportedChains returns a list of supported chains
	ListSupportedChains(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v2beta.ListSupportedChainsResponse], error)
	// GetChainTokens returns all tokens available on a specific chain
	// Includes both native tokens and IBC tokens with their denoms
	GetChainTokens(context.Context, *connect.Request[v2beta.GetChainTokensRequest]) (*connect.Response[v2beta.GetChainTokensResponse], error)
}

// NewPathfinderQueryServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPathfinderQueryServiceHandler(svc PathfinderQueryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pathfinderQueryServiceMethods := v2beta.File_pathfinder_v2beta_pathfinder_v2beta_query_proto.Services().ByName("PathfinderQueryService").Methods()
	pathfinderQueryServiceLookupDenomHandler := connect.NewUnaryHandler(
		PathfinderQueryServiceLookupDenomProcedure,
		svc.LookupDenom,
		connect.WithSchema(pathfinderQueryServiceMethods.ByName("LookupDenom")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	pathfinderQueryServiceGetTokenDenomsHandler := connect.NewUnaryHandler(
		PathfinderQueryServiceGetTokenDenomsProcedure,
		svc.GetTokenDenoms,
		connect.WithSchema(pathfinderQueryServiceMethods.ByName("GetTokenDenoms")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	pathfinderQueryServiceGetChainInfoHandler := connect.NewUnaryHandler(
		PathfinderQueryServiceGetChainInfoProcedure,
		svc.GetChainInfo,
		connect.WithSchema(pathfinderQueryServiceMethods.ByName("GetChainInfo")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	pathfinderQueryServiceListSupportedChainsHandler := connect.NewUnaryHandler(
		PathfinderQueryServiceListSupportedChainsProcedure,
		svc.ListSupportedChains,
		connect.WithSchema(pathfinderQueryServiceMethods.ByName("ListSupportedChains")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	pathfinderQueryServiceGetChainTokensHandler := connect.NewUnaryHandler(
		PathfinderQueryServiceGetChainTokensProcedure,
		svc.GetChainTokens,
		connect.WithSchema(pathfinderQueryServiceMethods.ByName("GetChainTokens")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/pathfinder.v2beta.PathfinderQueryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PathfinderQueryServiceLookupDenomProcedure:
			pathfinderQueryServiceLookupDenomHandler.ServeHTTP(w, r)
		case PathfinderQueryServiceGetTokenDenomsProcedure:
			pathfinderQueryServiceGetTokenDenomsHandler.ServeHTTP(w, r)
		case PathfinderQueryServiceGetChainInfoProcedure:
			pathfinderQueryServiceGetChainInfoHandler.ServeHTTP(w, r)
		case PathfinderQueryServiceListSupportedChainsProcedure:
			pathfinderQueryServiceListSupportedChainsHandler.ServeHTTP(w, r)
		case PathfinderQueryServiceGetChainTokensProcedure:
			pathfinderQueryServiceGetChainTokensHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPathfinderQueryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPathfinderQueryServiceHandler struct{}

func (UnimplementedPathfinderQueryServiceHandler) LookupDenom(context.Context, *connect.Request[v2beta.LookupDenomRequest]) (*connect.Response[v2beta.LookupDenomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pathfinder.v2beta.PathfinderQueryService.LookupDenom is not implemented"))
}

func (UnimplementedPathfinderQueryServiceHandler) GetTokenDenoms(context.Context, *connect.Request[v2beta.GetTokenDenomsRequest]) (*connect.Response[v2beta.GetTokenDenomsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pathfinder.v2beta.PathfinderQueryService.GetTokenDenoms is not implemented"))
}

func (UnimplementedPathfinderQueryServiceHandler) GetChainInfo(context.Context, *connect.Request[v2beta.GetChainInfoRequest]) (*connect.Response[v2beta.GetChainInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pathfinder.v2beta.PathfinderQueryService.GetChainInfo is not implemented"))
}

func (UnimplementedPathfinderQueryServiceHandler) ListSupportedChains(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v2beta.ListSupportedChainsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pathfinder.v2beta.PathfinderQueryService.ListSupportedChains is not implemented"))
}

func (UnimplementedPathfinderQueryServiceHandler) GetChainTokens(context.Context, *connect.Request[v2beta.GetChainTokensRequest]) (*connect.Response[v2beta.GetChainTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pathfinder.v2beta.PathfinderQueryService.GetChainTokens is not implemented"))
}
