// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pathfinder/v2beta/pathfinder_v2beta_find_path.proto

package v2betaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2beta "github.com/Cogwheel-Validator/spectra-portal/pathfinder/rpc/services/pathfinder/v2beta"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FindPathServiceName is the fully-qualified name of the FindPathService service.
	FindPathServiceName = "pathfinder.v2beta.FindPathService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FindPathServiceFindPathProcedure is the fully-qualified name of the FindPathService's FindPath
	// RPC.
	FindPathServiceFindPathProcedure = "/pathfinder.v2beta.FindPathService/FindPath"
	// FindPathServiceFindPathStreamingProcedure is the fully-qualified name of the FindPathService's
	// FindPathStreaming RPC.
	FindPathServiceFindPathStreamingProcedure = "/pathfinder.v2beta.FindPathService/FindPathStreaming"
)

// FindPathServiceClient is a client for the pathfinder.v2beta.FindPathService service.
type FindPathServiceClient interface {
	// FindPath finds and validates a route between two chains
	// Supports human-readable denoms (e.g., "uatone") or IBC denoms
	FindPath(context.Context, *connect.Request[v2beta.FindPathRequest]) (*connect.Response[v2beta.FindPathResponse], error)
	// FindPathStreaming is the bidirectional-streaming counterpart of FindPath
	FindPathStreaming(context.Context) *connect.BidiStreamForClient[v2beta.FindPathStreamingRequest, v2beta.FindPathStreamingResponse]
}

// NewFindPathServiceClient constructs a client for the pathfinder.v2beta.FindPathService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFindPathServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FindPathServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	findPathServiceMethods := v2beta.File_pathfinder_v2beta_pathfinder_v2beta_find_path_proto.Services().ByName("FindPathService").Methods()
	return &findPathServiceClient{
		findPath: connect.NewClient[v2beta.FindPathRequest, v2beta.FindPathResponse](
			httpClient,
			baseURL+FindPathServiceFindPathProcedure,
			connect.WithSchema(findPathServiceMethods.ByName("FindPath")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		findPathStreaming: connect.NewClient[v2beta.FindPathStreamingRequest, v2beta.FindPathStreamingResponse](
			httpClient,
			baseURL+FindPathServiceFindPathStreamingProcedure,
			connect.WithSchema(findPathServiceMethods.ByName("FindPathStreaming")),
			connect.WithClientOptions(opts...),
		),
	}
}

// findPathServiceClient implements FindPathServiceClient.
type findPathServiceClient struct {
	findPath          *connect.Client[v2beta.FindPathRequest, v2beta.FindPathResponse]
	findPathStreaming *connect.Client[v2beta.FindPathStreamingRequest, v2beta.FindPathStreamingResponse]
}

// FindPath calls pathfinder.v2beta.FindPathService.FindPath.
func (c *findPathServiceClient) FindPath(ctx context.Context, req *connect.Request[v2beta.FindPathRequest]) (*connect.Response[v2beta.FindPathResponse], error) {
	return c.findPath.CallUnary(ctx, req)
}

// FindPathStreaming calls pathfinder.v2beta.FindPathService.FindPathStreaming.
func (c *findPathServiceClient) FindPathStreaming(ctx context.Context) *connect.BidiStreamForClient[v2beta.FindPathStreamingRequest, v2beta.FindPathStreamingResponse] {
	return c.findPathStreaming.CallBidiStream(ctx)
}

// FindPathServiceHandler is an implementation of the pathfinder.v2beta.FindPathService service.
type FindPathServiceHandler interface {
	// FindPath finds and validates a route between two chains
	// Supports human-readable denoms (e.g., "uatone") or IBC denoms
	FindPath(context.Context, *connect.Request[v2beta.FindPathRequest]) (*connect.Response[v2beta.FindPathResponse], error)
	// FindPathStreaming is the bidirectional-streaming counterpart of FindPath
	FindPathStreaming(context.Context, *connect.BidiStream[v2beta.FindPathStreamingRequest, v2beta.FindPathStreamingResponse]) error
}

// NewFindPathServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFindPathServiceHandler(svc FindPathServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	findPathServiceMethods := v2beta.File_pathfinder_v2beta_pathfinder_v2beta_find_path_proto.Services().ByName("FindPathService").Methods()
	findPathServiceFindPathHandler := connect.NewUnaryHandler(
		FindPathServiceFindPathProcedure,
		svc.FindPath,
		connect.WithSchema(findPathServiceMethods.ByName("FindPath")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	findPathServiceFindPathStreamingHandler := connect.NewBidiStreamHandler(
		FindPathServiceFindPathStreamingProcedure,
		svc.FindPathStreaming,
		connect.WithSchema(findPathServiceMethods.ByName("FindPathStreaming")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pathfinder.v2beta.FindPathService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FindPathServiceFindPathProcedure:
			findPathServiceFindPathHandler.ServeHTTP(w, r)
		case FindPathServiceFindPathStreamingProcedure:
			findPathServiceFindPathStreamingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFindPathServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFindPathServiceHandler struct{}

func (UnimplementedFindPathServiceHandler) FindPath(context.Context, *connect.Request[v2beta.FindPathRequest]) (*connect.Response[v2beta.FindPathResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pathfinder.v2beta.FindPathService.FindPath is not implemented"))
}

func (UnimplementedFindPathServiceHandler) FindPathStreaming(context.Context, *connect.BidiStream[v2beta.FindPathStreamingRequest, v2beta.FindPathStreamingResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("pathfinder.v2beta.FindPathService.FindPathStreaming is not implemented"))
}
